M48
; DRILL file {KiCad (6.0.10)} date Sun Jun  9 15:04:41 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-09T15:04:41-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1083
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1575
%
G90
G05
T1
X2.9805Y-2.2061
X2.9805Y-4.4856
T2
X2.9528Y-5.4134
X5.748Y-1.811
X6.0236Y-4.6457
T0
M30
